vision:
  #  #camera 2--3
  #  width: 640
  #  height: 360
  camera_matrix: [[ 522.1905267183170736, 0.0000000000000000, 308.8532705794233948  ],
                  [ 0.0000000000000000, 522.8166355728753842, 234.2130798407917496 ],
                  [ 0.0000000000000000, 0.0000000000000000, 1.0000000000000000 ]]

  camera_dist: [ 0.1058497356483027 ,-0.1488874492570700 ,0.0000000000000000 ,0.0000000000000000 ,-0.8698561798572152]
  # marker_length: 0.012
  # marker_length: 0.0562
  marker_length: 0.006

  aruco_dict: '4X4_100'
